#include "gtest/gtest.h"
#include <iostream>
#include <iomanip>

//------------------------------------------------------------------------------
//Files we are testing:
#include "../../includes/sql/sql.h"



//------------------------------------------------------------------------------

using namespace std;

//------------------------------------------------------------------------------
//          COPY BASIC_TEST INTO THIS FILE.
//                    AND THEN,
//         DO NOT EDIT THIS FILE ANY FURTHER
//------------------------------------------------------------------------------

const vector<string> command_list = {
/*00*/     "create table employee fields  last,       first,         dep,      salary, year",
/*01*/     "insert into employee values Blow,       Joe,           CS,       100000, 2018",
/*02*/     "insert into employee values Blow,       JoAnn,         Physics,  200000, 2016",
/*03*/     "insert into employee values Johnson,    Jack,          HR,       150000, 2014",
/*04*/     "insert into employee values Johnson,    \"Jimmy\",     Chemistry,140000, 2018",

/*05*/     "create table student fields  fname,          lname,    major,    age",
/*06*/     "insert into student values Flo,            Yao, 	Art, 	20",
/*07*/     "insert into student values Bo, 		     Yang, 	CS, 		28",
/*08*/     "insert into student values \"Sammuel L.\", Jackson, 	CS, 		40",
/*09*/     "insert into student values \"Billy\",	     Jackson, 	Math,	27",
/*10*/     "insert into student values \"Mary Ann\",   Davis,	Math,	30",

/*11*/     "select * from employee",
/*12*/     "select last, first, age from employee",
/*13*/     "select last from employee",
/*14*/     "select * from employee where last = Johnson",
/*15*/     "select * from employee where last=Blow and major=\"JoAnn\"",

/*16*/     "select * from student",
/*17*/     "select * from student where (major=CS or major=Art)",
/*18*/     "select * from student where lname>J",
/*19*/     "select * from student where lname>J and (major=CS or major=Art)"
};

const int MAKE_TABLE_COMMANDS = 11;
const int SELECT_COMMANDS = 20;

bool sql_basic(bool debug = false)
{
  SQL sql;
  Table t;
  // create the tables
  cout << "> " << command_list[0] << endl;
  sql.command(command_list[0]);
  cout << "table is created" << endl << endl;
  // insert to the tables
  for (int i = 0; i < MAKE_TABLE_COMMANDS; i++) {
    cout << "> " << command_list[i] << endl;
    t = sql.command(command_list[i]);
  }

  cout << endl << endl;
  
  // select the tables
  for (int i = MAKE_TABLE_COMMANDS; i < command_list.size(); i++)
  {
    cout << "> " << command_list[i] << endl;
    t = sql.command(command_list[i]);
    if (debug) cout << t << endl;
    cout << "records selected: " << sql.select_recnos() << endl << endl;
  }

  return true;
}

bool sql_batch(bool debug = false)
{
  SQL sql;
  sql.batch((string("_!sample01.txt").c_str()));
  return true;
}

//Lord help me! 
const bool debug = false;

TEST(SQL_BASIC, SQLBasic)
{
  bool success = sql_basic(debug);
  EXPECT_EQ(success, true);
}

TEST(SQL_BASIC, SQLBatch)
{
  bool success = sql_batch(debug);
  EXPECT_EQ(success, true);
}


int main(int argc, char **argv)
{
  ::testing::InitGoogleTest(&argc, argv);
  std::cout<<"\n\n----------running basic_test.cpp---------\n\n"<<std::endl;
  return RUN_ALL_TESTS();
}


/*
includes
├── binary_files
|   ├── file_record.cpp
|   ├── file_record.h
|   ├── utilities.cpp
|   └── utilities.h
├── linked_list
│   ├── linked_list_functions
│   │   └── linked_list_functions.h
│   ├── node
│   │   └── node.h
│   ├── queue
│   │   └── MyQueue.h
│   └── stack
│       └── MyStack.h
├── map
│   ├── bplustree.h
│   ├── btree_array_functions.h
│   ├── map.h
│   ├── mmap.h
│   ├── mpair.h
│   └── pair.h
├── parser
|   ├── constants.h
│   ├── parser.cpp
│   └── parser.h
├── rpn
│   ├── rpn.cpp
│   └── rpn.h
├── shunting_yard
│   ├── shunting_yard.cpp
│   └── shunting_yard.h
├── sql
│   ├── sql.cpp
│   └── sql.h
├── table
│   ├── table.cpp
│   └── table.h
└── token
    ├── constants.h
    ├── leftparen.h
    ├── logical.h
    ├── relational.h
    ├── rightparen.h
    ├── token.h
    ├── tokenstr.h
    └── universal.h

9 directories, 33 files


----------running basic_test.cpp---------


[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from SQL_BASIC
[ RUN      ] SQL_BASIC.SQLBasic
FAILED: create table: table name cannot be empty
FAILED: create table: table name cannot be empty
> create table employee fields  last,       first,         dep,      salary, year
table is created

> create table employee fields  last,       first,         dep,      salary, year
FAILED: create table: employee table already exists
> insert into employee values Blow,       Joe,           CS,       100000, 2018
> insert into employee values Blow,       JoAnn,         Physics,  200000, 2016
> insert into employee values Johnson,    Jack,          HR,       150000, 2014
> insert into employee values Johnson,    "Jimmy",     Chemistry,140000, 2018
> create table student fields  fname,          lname,    major,    age
> insert into student values Flo,            Yao,       Art,    20
> insert into student values Bo,                     Yang,      CS,             28
> insert into student values "Sammuel L.", Jackson,     CS,             40
> insert into student values "Billy",        Jackson,   Math,   27
> insert into student values "Mary Ann",   Davis,       Math,   30


> select * from employee
records selected: 0 1 2 3 

> select last, first, age from employee
records selected: 0 1 2 3 

> select last from employee
records selected: 0 1 2 3 

> select * from employee where last = Johnson
records selected: 2 3 

> select * from employee where last=Blow and major="JoAnn"
records selected: 

> select * from student
records selected: 0 1 2 3 4 

> select * from student where (major=CS or major=Art)
records selected: 0 1 2 

> select * from student where lname>J
records selected: 2 3 1 0 

> select * from student where lname>J and (major=CS or major=Art)
records selected: 0 1 2 

[       OK ] SQL_BASIC.SQLBasic (21 ms)
[ RUN      ] SQL_BASIC.SQLBatch
FAILED: create table: table name cannot be empty
[0] > create table employeeSample01 fields  last,               first,                  dep
[1] > insert into employeeSample01 values Blow,                 Joe,                    CS
[2] > insert into employeeSample01 values Johnson,      "Jimmy",                Chemistry
[3] > insert into employeeSample01 values Yang,                 Bo,                     CS
[4] > insert into employeeSample01 values "Jackson",    Billy,                  Math
[5] > insert into employeeSample01 values Johnson,      Billy,                  "Phys Ed"
[6] > insert into employeeSample01 values "Van Gogh",   "Jim Bob",              "Phys Ed"
[7] > select * from employeeSample01 
Table name: _select_table_9, records: 6
                   record                     last                    first                      dep
                        0                     Blow                      Joe                       CS
                        1                  Johnson                    Jimmy                Chemistry
                        2                     Yang                       Bo                       CS
                        3                  Jackson                    Billy                     Math
                        4                  Johnson                    Billy                  Phys Ed
                        5                 Van Gogh                  Jim Bob                  Phys Ed
records selected: 0 1 2 3 4 5 

[8] > create table studentSample01 fields       fname,                  lname,          major,                          age
[9] > insert into studentSample01 values        Flo,                    Yao,            CS,                             20
[10] > insert into studentSample01 values       "Flo",                  "Jackson",      Math,                           21
[11] > insert into studentSample01 values       Calvin,                 Woo,            Physics,                        22
[12] > insert into studentSample01 values       "Anna Grace",   "Del Rio",      CS,                                     22
[13] > select * from studentSample01
Table name: _select_table_10, records: 4
                   record                    fname                    lname                    major                      age
                        0                      Flo                      Yao                       CS                       20
                        1                      Flo                  Jackson                     Math                       21
                        2                   Calvin                      Woo                  Physics                       22
                        3               Anna Grace                  Del Rio                       CS                       22
records selected: 0 1 2 3 

[14] > select * from studentSample01
Table name: _select_table_11, records: 4
                   record                    fname                    lname                    major                      age
                        0                      Flo                      Yao                       CS                       20
                        1                      Flo                  Jackson                     Math                       21
                        2                   Calvin                      Woo                  Physics                       22
                        3               Anna Grace                  Del Rio                       CS                       22
records selected: 0 1 2 3 

[15] > select * from studentSample01 where lname = Jackson
Table name: _select_table_12, records: 1
                   record                    fname                    lname                    major                      age
                        0                      Flo                  Jackson                     Math                       21
records selected: 1 

[16] > select * from studentSample01 where lname = "Del Rio"
Table name: _select_table_13, records: 1
                   record                    fname                    lname                    major                      age
                        0               Anna Grace                  Del Rio                       CS                       22
records selected: 3 

[17] > select * from studentSample01 where lname = "Does Not Exist"
Table name: _select_table_14, records: 0
                   record                    fname                    lname                    major                      age
records selected: 

[18] > select * from studentSample01 where lname > Yang
Table name: _select_table_15, records: 1
                   record                    fname                    lname                    major                      age
                        0                      Flo                      Yao                       CS                       20
records selected: 0 

[19] > select * from studentSample01 where age > 50
Table name: _select_table_16, records: 0
                   record                    fname                    lname                    major                      age
records selected: 

[20] > select * from studentSample01 where age  > 53
Table name: _select_table_17, records: 0
                   record                    fname                    lname                    major                      age
records selected: 

[21] > select * from studentSample01 where age > 54
Table name: _select_table_18, records: 0
                   record                    fname                    lname                    major                      age
records selected: 

[22] > select * from studentSample01 where lname >= Yang
Table name: _select_table_19, records: 1
                   record                    fname                    lname                    major                      age
                        0                      Flo                      Yao                       CS                       20
records selected: 0 

[23] > select * from employeeSample01 where last >= Jack
Table name: _select_table_20, records: 5
                   record                     last                    first                      dep
                        0                  Jackson                    Billy                     Math
                        1                  Johnson                    Jimmy                Chemistry
                        2                  Johnson                    Billy                  Phys Ed
                        3                 Van Gogh                  Jim Bob                  Phys Ed
                        4                     Yang                       Bo                       CS
records selected: 3 1 4 5 2 

[24] > select * from studentSample01 where lname < Jackson
Table name: _select_table_21, records: 1
                   record                    fname                    lname                    major                      age
                        0               Anna Grace                  Del Rio                       CS                       22
records selected: 3 

[25] > select * from studentSample01 where age  < 20
Table name: _select_table_22, records: 0
                   record                    fname                    lname                    major                      age
records selected: 

[26] > select * from studentSample01 where age  < 19
Table name: _select_table_23, records: 0
                   record                    fname                    lname                    major                      age
records selected: 

[27] > select * from studentSample01 where lname <= Smith
Table name: _select_table_24, records: 2
                   record                    fname                    lname                    major                      age
                        0               Anna Grace                  Del Rio                       CS                       22
                        1                      Flo                  Jackson                     Math                       21
records selected: 3 1 

[28] > select * from employeeSample01 where last <= Peach
Table name: _select_table_25, records: 4
                   record                     last                    first                      dep
                        0                     Blow                      Joe                       CS
                        1                  Jackson                    Billy                     Math
                        2                  Johnson                    Jimmy                Chemistry
                        3                  Johnson                    Billy                  Phys Ed
records selected: 0 3 1 4 

[29] > select * from studentSample01 where fname = "Flo" and lname = "Yao"
Table name: _select_table_26, records: 1
                   record                    fname                    lname                    major                      age
                        0                      Flo                      Yao                       CS                       20
records selected: 0 

[30] > select * from studentSample01 where fname = Flo or lname = Jackson
Table name: _select_table_27, records: 2
                   record                    fname                    lname                    major                      age
                        0                      Flo                      Yao                       CS                       20
                        1                      Flo                  Jackson                     Math                       21
records selected: 0 1 

[31] > select * from studentSample01 where fname = Flo or major = CS and age <= 23
Table name: _select_table_28, records: 3
                   record                    fname                    lname                    major                      age
                        0                      Flo                      Yao                       CS                       20
                        1                      Flo                  Jackson                     Math                       21
                        2               Anna Grace                  Del Rio                       CS                       22
records selected: 0 1 3 

[32] > select * from studentSample01 where age <30 and major=CS or major = Physics and lname = Jackson
Table name: _select_table_29, records: 2
                   record                    fname                    lname                    major                      age
                        0                      Flo                      Yao                       CS                       20
                        1               Anna Grace                  Del Rio                       CS                       22
records selected: 0 3 

[33] > select * from studentSample01 where lname = Yang or major = CS and age < 23 or lname = Jackson
Table name: _select_table_30, records: 3
                   record                    fname                    lname                    major                      age
                        0                      Flo                      Yao                       CS                       20
                        1                      Flo                  Jackson                     Math                       21
                        2               Anna Grace                  Del Rio                       CS                       22
records selected: 0 1 3 

[       OK ] SQL_BASIC.SQLBatch (79 ms)
[----------] 2 tests from SQL_BASIC (100 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (101 ms total)
[  PASSED  ] 2 tests.
*/