#include "gtest/gtest.h"
#include <iostream>
#include <iomanip>

//------------------------------------------------------------------------------
//Files we are testing:
#include "../../includes/heap/pqueue.h"
#include "../../includes/heap/info.h"
#include "../../includes/heap/heap.h"

//------------------------------------------------------------------------------

using namespace std;

//------------------------------------------------------------------------------
//          COPY BASIC_TEST INTO THIS FILE.
//                    AND THEN,
//         DO NOT EDIT THIS FILE ANY FURTHER
//------------------------------------------------------------------------------

const string LINE = "\n"+string(50,'-')+"\n";
const string DASH = "\n"+string(50,'.')+"\n";

bool test_heap(bool debug=false)
{
  cout << "\nPriority Queue Test" << endl << LINE << endl;

  PQueue<string> pq;
  pq.push("joe", 3);
  pq.push("bob", 1);
  pq.push("jack", 4);
  pq.push("betty", 5);
  pq.push("Kathy", 6);
  pq.push("Jose", 8);
  pq.push("Kathe", 6);
  pq.push("bill", 2);
  pq.push("Marie", 0);
  pq.push("sam bill", 2);
  pq.push("KathyTarde", 6);
  pq.push("Jose later", 8);
  pq.push("bill 1", 2);
  pq.push("bill 2", 2);
  pq.push("Marie's sister", 0);
  pq.push("sam dunk", 2);
  cout << pq << DASH << endl;
  while (!pq.empty())
  {
    cout << "POPPED: " << pq.top() << endl;
    pq.pop();
  }

  cout << LINE << endl;

  PQueue<int> pqi;
  pqi.push(5, 1);
  pqi.push(1, 1);
  pqi.push(7, 1);
  pqi.push(2, 3);
  pqi.push(9, 2);
  pqi.push(5, 3);
  cout << pqi << DASH << endl;
  while (!pqi.empty())
  {
    cout << "POPPED: " << pqi.top() << endl;
    pqi.pop();
  }

  cout << LINE << endl;

  return true;
}


//Lord help me! 
const bool debug = false;

TEST(BASIC_TES, TestHeap)
{
  bool success = test_heap(debug);
  EXPECT_EQ(success, true);
}


int main(int argc, char **argv)
{
  ::testing::InitGoogleTest(&argc, argv);
  std::cout<<"\n\n----------running basic_test.cpp---------\n\n"<<std::endl;
  return RUN_ALL_TESTS();
}

/*
includes
└── heap
    ├── heap.h
    ├── info.h
    └── pqueue.h

1 directory, 3 files

----------running basic_test.cpp---------


[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from BASIC_TES
[ RUN      ] BASIC_TES.TestHeap

Priority Queue Test

--------------------------------------------------

            Marie's sister
        Kathe
            bill 2
    Jose
            bill 1
        Kathy
            joe
Jose later
            jack
        betty
            sam bill
    KathyTarde
            Marie
        sam dunk
            bill
                bob

..................................................

POPPED: Jose later
POPPED: Jose
POPPED: KathyTarde
POPPED: Kathy
POPPED: Kathe
POPPED: betty
POPPED: jack
POPPED: joe
POPPED: sam dunk
POPPED: sam bill
POPPED: bill 2
POPPED: bill 1
POPPED: bill
POPPED: bob
POPPED: Marie's sister
POPPED: Marie

--------------------------------------------------

    2
        5
5
        7
    9
        1

..................................................

POPPED: 5
POPPED: 2
POPPED: 9
POPPED: 7
POPPED: 5
POPPED: 1

--------------------------------------------------

[       OK ] BASIC_TES.TestHeap (1 ms)
[----------] 1 test from BASIC_TES (1 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (1 ms total)
[  PASSED  ] 1 test.
*/