#include "gtest/gtest.h"
#include <iostream> // cout, endl
#include <iomanip>  // setw
#include <vector>   // vector

//------------------------------------------------------------------------------------------
//Files we are testing:
#include "../../includes/table/table.h"



//------------------------------------------------------------------------------------------

using namespace std;

//------------------------------------------------------------------------------
//          COPY BASIC_TEST INTO THIS FILE.
//                    AND THEN,
//         DO NOT EDIT THIS FILE ANY FURTHER
//------------------------------------------------------------------------------

const string LINE = "\n"+string(50,'-')+"\n";
const string DASH = "\n"+string(50,'.')+"\n";

Table make_table()
{
  // initialize fields of table
  vector<string> fields={"fname", "lname", "age"};
  // create table
  Table t("student", fields);
  // insert rows into table
  vector<string> row;
  row = {"Joe", "Gomez", "20"};
  t.insert_into(row);
  row = {"Karen", "Orozco", "21"};
  t.insert_into(row);
  row = {"Flo", "Yao", "29"};
  t.insert_into(row);
  row = {"Jack", "Yao", "19"};
  t.insert_into(row);
  row = {"Flo", "Jackson", "20"};
  t.insert_into(row);
  row = {"Flo", "Gomez", "20"};
  t.insert_into(row);
  row = {"Karen", "Jackson", "15"};
  t.insert_into(row);
  row = {"Flo", "Jones", "16"};
  t.insert_into(row);
  return t;
}

bool table_shunting_yard(bool debug = false)
{
  // initialize infix queue
  Queue<Token*> infix;
  // push condition into infix queue
  infix.push(new LeftParen());
  infix.push(new TokenStr("age"));
  infix.push(new Relational("<"));
  infix.push(new TokenStr("20"));
  infix.push(new Logical("or"));
  infix.push(new TokenStr("age"));
  infix.push(new Relational(">="));
  infix.push(new TokenStr("25"));
  infix.push(new RightParen());
  infix.push(new Logical("and"));
  infix.push(new TokenStr("fname"));
  infix.push(new Relational("="));
  infix.push(new TokenStr("Flo"));
  // create shunting yard object
  ShuntingYard sy(infix);
  // get postfix queue
  Queue<Token*> postfix = sy.postfix();
  // print infix and postfix
  cout << LINE;
  cout << "condition: ( age < 20 or age >= 25 ) and fname = Flo" << endl;
  cout << "infix:   " << infix;
  cout << "postfix: " << postfix;

  // initialize infix queue
  infix = Queue<Token*>();
  // push condition into infix queue
  infix.push(new TokenStr("age"));
  infix.push(new Relational("<="));
  infix.push(new TokenStr("20"));
  infix.push(new Logical("or"));
  infix.push(new TokenStr("age"));
  infix.push(new Relational(">"));
  infix.push(new TokenStr("25"));
  infix.push(new Logical("and"));
  infix.push(new TokenStr("fname"));
  infix.push(new Relational("="));
  infix.push(new TokenStr("Flo"));
  // create shunting yard object
  sy = ShuntingYard(infix);
  // get postfix queue
  postfix = sy.postfix();
  // print infix and postfix
  cout << LINE;
  cout << "condition: age <= 20 or age > 25 and fname = Flo" << endl;
  cout << "infix:   " << infix;
  cout << "postfix: " << postfix;

  cout << LINE;

  return true;
}

bool table_basic(bool debug = false)
{
  // create table
  Table t = make_table();
  // print table
  cout << "\nHere is the table:" << LINE << t << LINE << endl;

  cout << "Here are all the Yaos:";
  cout << LINE << t.select({"fname", "lname", "age"}, "lname", "=", "Yao") << DASH;
  cout << "record numbers from original table: "<< t.select_recnos() << LINE << endl;

  // select student table
  Table tbl_student("student");
  cout << "Here is the student table:" << LINE << tbl_student << LINE << endl;

  cout << "20 years old:";
  cout << LINE << tbl_student.select({"age", "fname", "lname"}, "age", "=", "20") << DASH;
  cout << "record numbers from original table: "<< tbl_student.select_recnos() << LINE << endl;

  cout << "older than 20 years old:";
  cout << LINE << tbl_student.select({"age", "fname", "lname"}, "age", ">", "20") << DASH;
  cout << "record numbers from original table: "<< tbl_student.select_recnos() << LINE << endl;

  cout << "younger than 20 years old:";
  cout << LINE << tbl_student.select({"age", "fname", "lname"}, "age", "<", "20") << DASH;
  cout << "record numbers from original table: "<< tbl_student.select_recnos() << LINE << endl;

  cout << "20 or younger:";
  cout << LINE << tbl_student.select({"age", "fname", "lname"}, "age", "<=", "20") << DASH;
  cout << "record numbers from original table: "<< tbl_student.select_recnos() << LINE << endl;

  cout << "20 or older:";
  cout << LINE << tbl_student.select({"age", "fname", "lname"}, "age", ">=", "20") << DASH;
  cout << "record numbers from original table: "<< tbl_student.select_recnos() << LINE << endl;

  return true;
}

bool table_condition(bool debug = false)
{
  // select student table
  Table t("student");
  // print table
  cout << "\nHere is the table:" << LINE << t << LINE << endl;

  // test table relational operators

  // initialize queue of tokens
  Queue<Token *> post;
  post.push(new TokenStr("lname"));
  post.push(new TokenStr("Yao"));
  post.push(new Relational("="));
  // create selected table
  Table selected = t.select({"lname", "age"}, post);
  // print selected table
  cout << "Here are all the Yaos:";
  cout << LINE << selected << DASH;
  cout << "record numbers from original table: " << t.select_recnos() << LINE << endl;

  // test table logical operators

  // initialize queue of tokens
  post = Queue<Token *>();
  post.push(new TokenStr("age"));
  post.push(new TokenStr("20"));
  post.push(new Relational("<="));
  post.push(new TokenStr("age"));
  post.push(new TokenStr("17"));
  post.push(new Relational(">="));
  post.push(new Logical("and"));
  // create selected table
  selected = t.select({"lname", "age"}, post);
  // print selected table
  cout << "all the 17 to 20 year olds:";
  cout << LINE << selected << DASH;
  cout << "record numbers from original table:" << t.select_recnos() << LINE << endl;

  // test table with full condition

  // initialize queue of tokens
  post = Queue<Token *>();
  post.push(new TokenStr("age"));
  post.push(new TokenStr("20"));
  post.push(new Relational("<"));
  post.push(new TokenStr("age"));
  post.push(new TokenStr("17"));
  post.push(new Relational(">"));
  post.push(new Logical("and"));
  post.push(new TokenStr("lname"));
  post.push(new TokenStr("Gomez"));
  post.push(new Relational("="));
  post.push(new Logical("or"));
  // create selected table
  selected = t.select({"lname", "age"}, post);
  // print selected table
  cout << "all the 17 to 20 year olds (non inclusive) along with all the Gomezes:";
  cout << LINE << selected << DASH;
  cout << "record numbers from original table: " << t.select_recnos() << LINE << endl;

  // test table condition from strings

  // initialize vector of strings
  vector<string> condition = {"(", "age", "<", "17", "or", "age", ">", "20", ")", "and", "lname", "=", "Jackson"};
  // create selected table
  selected = t.select({"lname", "age"}, condition);
  // print selected table
  cout << "all younger than 17, all older than 20, who are Jacksons:";
  cout << LINE << selected << DASH;
  cout << "record numbers from original table: " << t.select_recnos() << LINE << endl;

  return true;
}

TEST(TABLE_BASIC, TableShuntingYard)
{
  bool success = table_shunting_yard();
  EXPECT_EQ(success, true);
}

TEST(TABLE_ADVANCED, TableBasic)
{
  bool success = table_basic();
  EXPECT_EQ(success, true);
}

TEST(TABLE_ADVANCED, TableCondition)
{
  bool success = table_condition(false);
  EXPECT_EQ(success, true);
}


int main(int argc, char **argv)
{
  ::testing::InitGoogleTest(&argc, argv);
  std::cout<<"\n\n----------running basic_test.cpp---------\n\n"<<std::endl;
  return RUN_ALL_TESTS();
}



/*
includes
├── binary_files
|   ├── file_record.cpp
|   ├── file_record.h
|   ├── utilities.cpp
|   └── utilities.h
├── linked_list
│   ├── linked_list_functions
│   │   └── linked_list_functions.h
│   ├── node
│   │   └── node.h
│   ├── queue
│   │   └── MyQueue.h
│   └── stack
│       └── MyStack.h
├── map
│   ├── bplustree.h
│   ├── btree_array_functions.h
│   ├── map.h
│   ├── mmap.h
│   ├── mpair.h
│   └── pair.h
├── rpn
│   ├── rpn.cpp
│   └── rpn.h
├── shunting_yard
│   ├── shunting_yard.cpp
│   └── shunting_yard.h
├── table
│   ├── table.cpp
│   └── table.h
└── token
    ├── constants.h
    ├── leftparen.h
    ├── logical.h
    ├── relational.h
    ├── rightparen.h
    ├── token.h
    ├── tokenstr.h
    └── universal.h

7 directories, 28 files


----------running basic_test.cpp---------


[==========] Running 3 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 1 test from TABLE_BASIC
[ RUN      ] TABLE_BASIC.TableShuntingYard

--------------------------------------------------
condition: ( age < 20 or age >= 25 ) and fname = Flo
infix:   Head-><-[(]-><-[age]-><-[<]-><-[20]-><-[or]-><-[age]-><-[>=]-><-[25]-><-[)]-><-[and]-><-[fname]-><-[=]-><-[Flo]->|||
postfix: Head-><-[age]-><-[20]-><-[<]-><-[age]-><-[25]-><-[>=]-><-[or]-><-[fname]-><-[Flo]-><-[=]-><-[and]->|||

--------------------------------------------------
condition: age <= 20 or age > 25 and fname = Flo
infix:   Head-><-[age]-><-[<=]-><-[20]-><-[or]-><-[age]-><-[>]-><-[25]-><-[and]-><-[fname]-><-[=]-><-[Flo]->|||
postfix: Head-><-[age]-><-[20]-><-[<=]-><-[age]-><-[25]-><-[>]-><-[fname]-><-[Flo]-><-[=]-><-[and]-><-[or]->|||

--------------------------------------------------
[       OK ] TABLE_BASIC.TableShuntingYard (0 ms)
[----------] 1 test from TABLE_BASIC (0 ms total)

[----------] 2 tests from TABLE_ADVANCED
[ RUN      ] TABLE_ADVANCED.TableBasic

Here is the table:
--------------------------------------------------
Table name: student, records: 8
                   record                    fname                    lname                      age
                        0                      Joe                    Gomez                       20
                        1                    Karen                   Orozco                       21
                        2                      Flo                      Yao                       29
                        3                     Jack                      Yao                       19
                        4                      Flo                  Jackson                       20
                        5                      Flo                    Gomez                       20
                        6                    Karen                  Jackson                       15
                        7                      Flo                    Jones                       16

--------------------------------------------------

Here are all the Yaos:
--------------------------------------------------
Table name: _select_table_0, records: 2
                   record                    fname                    lname                      age
                        0                      Flo                      Yao                       29
                        1                     Jack                      Yao                       19

..................................................
record numbers from original table: 2 3 
--------------------------------------------------

Here is the student table:
--------------------------------------------------
Table name: student, records: 8
                   record                    fname                    lname                      age
                        0                      Joe                    Gomez                       20
                        1                    Karen                   Orozco                       21
                        2                      Flo                      Yao                       29
                        3                     Jack                      Yao                       19
                        4                      Flo                  Jackson                       20
                        5                      Flo                    Gomez                       20
                        6                    Karen                  Jackson                       15
                        7                      Flo                    Jones                       16

--------------------------------------------------

20 years old:
--------------------------------------------------
Table name: _select_table_1, records: 3
                   record                      age                    fname                    lname
                        0                       20                      Joe                    Gomez
                        1                       20                      Flo                  Jackson
                        2                       20                      Flo                    Gomez

..................................................
record numbers from original table: 0 4 5 
--------------------------------------------------

older than 20 years old:
--------------------------------------------------
Table name: _select_table_2, records: 2
                   record                      age                    fname                    lname
                        0                       21                    Karen                   Orozco
                        1                       29                      Flo                      Yao

..................................................
record numbers from original table: 1 2 
--------------------------------------------------

younger than 20 years old:
--------------------------------------------------
Table name: _select_table_3, records: 3
                   record                      age                    fname                    lname
                        0                       15                    Karen                  Jackson
                        1                       16                      Flo                    Jones
                        2                       19                     Jack                      Yao

..................................................
record numbers from original table: 6 7 3 
--------------------------------------------------

20 or younger:
--------------------------------------------------
Table name: _select_table_4, records: 6
                   record                      age                    fname                    lname
                        0                       15                    Karen                  Jackson
                        1                       16                      Flo                    Jones
                        2                       19                     Jack                      Yao
                        3                       20                      Joe                    Gomez
                        4                       20                      Flo                  Jackson
                        5                       20                      Flo                    Gomez

..................................................
record numbers from original table: 6 7 3 0 4 5 
--------------------------------------------------

20 or older:
--------------------------------------------------
Table name: _select_table_5, records: 5
                   record                      age                    fname                    lname
                        0                       20                      Joe                    Gomez
                        1                       20                      Flo                  Jackson
                        2                       20                      Flo                    Gomez
                        3                       21                    Karen                   Orozco
                        4                       29                      Flo                      Yao

..................................................
record numbers from original table: 0 4 5 1 2 
--------------------------------------------------

[       OK ] TABLE_ADVANCED.TableBasic (11 ms)
[ RUN      ] TABLE_ADVANCED.TableCondition

Here is the table:
--------------------------------------------------
Table name: student, records: 8
                   record                    fname                    lname                      age
                        0                      Joe                    Gomez                       20
                        1                    Karen                   Orozco                       21
                        2                      Flo                      Yao                       29
                        3                     Jack                      Yao                       19
                        4                      Flo                  Jackson                       20
                        5                      Flo                    Gomez                       20
                        6                    Karen                  Jackson                       15
                        7                      Flo                    Jones                       16

--------------------------------------------------

Here are all the Yaos:
--------------------------------------------------
Table name: _select_table_6, records: 2
                   record                    lname                      age
                        0                      Yao                       29
                        1                      Yao                       19

..................................................
record numbers from original table: 2 3 
--------------------------------------------------

all the 17 to 20 year olds:
--------------------------------------------------
Table name: _select_table_7, records: 4
                   record                    lname                      age
                        0                    Gomez                       20
                        1                      Yao                       19
                        2                  Jackson                       20
                        3                    Gomez                       20

..................................................
record numbers from original table:0 3 4 5 
--------------------------------------------------

all the 17 to 20 year olds (non inclusive) along with all the Gomezes:
--------------------------------------------------
Table name: _select_table_8, records: 3
                   record                    lname                      age
                        0                    Gomez                       20
                        1                      Yao                       19
                        2                    Gomez                       20

..................................................
record numbers from original table: 0 3 5 
--------------------------------------------------

all younger than 17, all older than 20, who are Jacksons:
--------------------------------------------------
Table name: _select_table_9, records: 1
                   record                    lname                      age
                        0                  Jackson                       15

..................................................
record numbers from original table: 6 
--------------------------------------------------

[       OK ] TABLE_ADVANCED.TableCondition (6 ms)
[----------] 2 tests from TABLE_ADVANCED (17 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 2 test suites ran. (17 ms total)
[  PASSED  ] 3 tests.
*/