#include "gtest/gtest.h"
#include <cmath>
#include <iostream>
#include <iomanip>

//------------------------------------------------------------------------------------------
//Files we are testing:
#include "../../includes/tokenizer/stokenize.h"
#include "../../includes/tokenizer/ftokenize.h"


//------------------------------------------------------------------------------------------

using namespace std;

//------------------------------------------------------------------------------
//          COPY BASIC_TEST INTO THIS FILE.
//                    AND THEN,
//         DO NOT EDIT THIS FILE ANY FURTHER
//------------------------------------------------------------------------------

bool test_s_tokenize(bool debug = false)
{
  // initialization
  char s[] = "So, it was the night of october 17th. pi was still 3.14. sigh! 2.";
  cout << "\nTokenizing: " << s << endl << endl;
  STokenizer stk(s);
  SToken t;

  // process the first token
  stk >> t;
  // keep precessing token
  while(stk.more()){
    // process token here...
    cout << setw(10) << t.token_type() << setw(10) << t << endl;
    t = SToken();
    stk >> t;
  }
  
  return true;
}

bool test_f_tokenize(bool debug = false)
{
  //****************************
  //========================== *
  //= set MAX_BUFFER to 200  = *
  //=    For this run        = *
  //========================== *
  //****************************
  
  // initialization
  FTokenizer ftk("solitude_mini.txt");
  SToken t;
  int token_count = 0;

  // process the first token
  ftk >> t;
  // keep precessing token
  while (ftk.more()) {
    // process token here...
    if (t.token_type()=="ALPHA" ) {
      token_count++;
      // if (token_count == 100) break;
      cout<<setw(10)<<right<<token_count<<setw(3)<<left<<":"
          <<setw(25)<<left<<t.token_str()<<t.token_type()<<setw(20)<<right<<strlen(t.token_str().c_str())<<endl;
    }
    ftk >> t;
  }
  cout << "Tokens Found: " << token_count << endl;
  cout << "==========" << endl;

  return true;
}


//Lord help me! 
const bool debug = false;

TEST(TEST_TOKENIZER, TestSTokenize)
{
  bool success = test_s_tokenize(debug);
  EXPECT_EQ(success, true);
}

TEST(TEST_TOKENIZER, TestFTokenize)
{
  bool success = test_f_tokenize(debug);
  EXPECT_EQ(success, true);
}

int main(int argc, char **argv)
{
  ::testing::InitGoogleTest(&argc, argv);
  std::cout<<"\n\n----------running basic_test.cpp---------\n\n"<<std::endl;
  return RUN_ALL_TESTS();
}

/*
includes
└── tokenizer
    ├── constants.h
    ├── ftokenize.cpp
    ├── ftokenize.h
    ├── state_machine_functions.cpp
    ├── state_machine_functions.h
    ├── stokenize.cpp
    ├── stokenize.h
    ├── token.cpp
    └── token.h

1 directory, 9 files


----------running basic_test.cpp---------


[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from TEST_TOKENIZER
[ RUN      ] TEST_TOKENIZER.TestSTokenize

Tokenizing: So, it was the night of october 17th. pi was still 3.14. sigh! 2.

     ALPHA         |So|
      PUNC         |,|
     SPACE         | |
     ALPHA         |it|
     SPACE         | |
     ALPHA         |was|
     SPACE         | |
     ALPHA         |the|
     SPACE         | |
     ALPHA         |night|
     SPACE         | |
     ALPHA         |of|
     SPACE         | |
     ALPHA         |october|
     SPACE         | |
    NUMBER         |17|
     ALPHA         |th|
      PUNC         |.|
     SPACE         | |
     ALPHA         |pi|
     SPACE         | |
     ALPHA         |was|
     SPACE         | |
     ALPHA         |still|
     SPACE         | |
    NUMBER         |3.14|
      PUNC         |.|
     SPACE         | |
     ALPHA         |sigh|
      PUNC         |!|
     SPACE         | |
    NUMBER         |2|
      PUNC         |.|
[       OK ] TEST_TOKENIZER.TestSTokenize (0 ms)
[ RUN      ] TEST_TOKENIZER.TestFTokenize
Reading ../../solitude_mini.txt

----- New Block ---------------------[199] bytes

Chapter 1
MANY YEARS LATER as he faced the firing squad, Colonel Aureliano Buend�a was to remember that distant afternoon when his father took him to discover ice. At that time Macondo was a villa
         1:  Chapter                  ALPHA                   7
         2:  MANY                     ALPHA                   4
         3:  YEARS                    ALPHA                   5
         4:  LATER                    ALPHA                   5
         5:  as                       ALPHA                   2
         6:  he                       ALPHA                   2
         7:  faced                    ALPHA                   5
         8:  the                      ALPHA                   3
         9:  firing                   ALPHA                   6
        10:  squad                    ALPHA                   5
        11:  Colonel                  ALPHA                   7
        12:  Aureliano                ALPHA                   9
        13:  Buend                    ALPHA                   5
        14:  a                        ALPHA                   1
        15:  was                      ALPHA                   3
        16:  to                       ALPHA                   2
        17:  remember                 ALPHA                   8
        18:  that                     ALPHA                   4
        19:  distant                  ALPHA                   7
        20:  afternoon                ALPHA                   9
        21:  when                     ALPHA                   4
        22:  his                      ALPHA                   3
        23:  father                   ALPHA                   6
        24:  took                     ALPHA                   4
        25:  him                      ALPHA                   3
        26:  to                       ALPHA                   2
        27:  discover                 ALPHA                   8
        28:  ice                      ALPHA                   3
        29:  At                       ALPHA                   2
        30:  that                     ALPHA                   4
        31:  time                     ALPHA                   4
        32:  Macondo                  ALPHA                   7
        33:  was                      ALPHA                   3
        34:  a                        ALPHA                   1
        35:  villa                    ALPHA                   5
----- New Block ---------------------[199] bytes
ge of twenty adobe houses, built on the bank of a river of clear water that ran along a bed of polished stones, which were white and enormous, like prehistoric eggs. 

The world was so recent that ma
        36:  ge                       ALPHA                   2
        37:  of                       ALPHA                   2
        38:  twenty                   ALPHA                   6
        39:  adobe                    ALPHA                   5
        40:  houses                   ALPHA                   6
        41:  built                    ALPHA                   5
        42:  on                       ALPHA                   2
        43:  the                      ALPHA                   3
        44:  bank                     ALPHA                   4
        45:  of                       ALPHA                   2
        46:  a                        ALPHA                   1
        47:  river                    ALPHA                   5
        48:  of                       ALPHA                   2
        49:  clear                    ALPHA                   5
        50:  water                    ALPHA                   5
        51:  that                     ALPHA                   4
        52:  ran                      ALPHA                   3
        53:  along                    ALPHA                   5
        54:  a                        ALPHA                   1
        55:  bed                      ALPHA                   3
        56:  of                       ALPHA                   2
        57:  polished                 ALPHA                   8
        58:  stones                   ALPHA                   6
        59:  which                    ALPHA                   5
        60:  were                     ALPHA                   4
        61:  white                    ALPHA                   5
        62:  and                      ALPHA                   3
        63:  enormous                 ALPHA                   8
        64:  like                     ALPHA                   4
        65:  prehistoric              ALPHA                  11
        66:  eggs                     ALPHA                   4
        67:  The                      ALPHA                   3
        68:  world                    ALPHA                   5
        69:  was                      ALPHA                   3
        70:  so                       ALPHA                   2
        71:  recent                   ALPHA                   6
        72:  that                     ALPHA                   4
        73:  ma                       ALPHA                   2
----- New Block ---------------------[199] bytes
ny things lacked names, and in order to indicate them it was necessary to point. Every year during the month of March a family of ragged gypsies would set up their tents near the village, and with a 
        74:  ny                       ALPHA                   2
        75:  things                   ALPHA                   6
        76:  lacked                   ALPHA                   6
        77:  names                    ALPHA                   5
        78:  and                      ALPHA                   3
        79:  in                       ALPHA                   2
        80:  order                    ALPHA                   5
        81:  to                       ALPHA                   2
        82:  indicate                 ALPHA                   8
        83:  them                     ALPHA                   4
        84:  it                       ALPHA                   2
        85:  was                      ALPHA                   3
        86:  necessary                ALPHA                   9
        87:  to                       ALPHA                   2
        88:  point                    ALPHA                   5
        89:  Every                    ALPHA                   5
        90:  year                     ALPHA                   4
        91:  during                   ALPHA                   6
        92:  the                      ALPHA                   3
        93:  month                    ALPHA                   5
        94:  of                       ALPHA                   2
        95:  March                    ALPHA                   5
        96:  a                        ALPHA                   1
        97:  family                   ALPHA                   6
        98:  of                       ALPHA                   2
        99:  ragged                   ALPHA                   6
       100:  gypsies                  ALPHA                   7
       101:  would                    ALPHA                   5
       102:  set                      ALPHA                   3
       103:  up                       ALPHA                   2
       104:  their                    ALPHA                   5
       105:  tents                    ALPHA                   5
       106:  near                     ALPHA                   4
       107:  the                      ALPHA                   3
       108:  village                  ALPHA                   7
       109:  and                      ALPHA                   3
       110:  with                     ALPHA                   4
       111:  a                        ALPHA                   1
----- New Block ---------------------[199] bytes
great uproar of pipes and kettledrums they would display new inventions. First they brought the magnet. A heavy gypsy with an untamed beard and sparrow hands, who introduced himself as Melqu�ades, 
       112:  great                    ALPHA                   5
       113:  uproar                   ALPHA                   6
       114:  of                       ALPHA                   2
       115:  pipes                    ALPHA                   5
       116:  and                      ALPHA                   3
       117:  kettledrums              ALPHA                  11
       118:  they                     ALPHA                   4
       119:  would                    ALPHA                   5
       120:  display                  ALPHA                   7
       121:  new                      ALPHA                   3
       122:  inventions               ALPHA                  10
       123:  First                    ALPHA                   5
       124:  they                     ALPHA                   4
       125:  brought                  ALPHA                   7
       126:  the                      ALPHA                   3
       127:  magnet                   ALPHA                   6
       128:  A                        ALPHA                   1
       129:  heavy                    ALPHA                   5
       130:  gypsy                    ALPHA                   5
       131:  with                     ALPHA                   4
       132:  an                       ALPHA                   2
       133:  untamed                  ALPHA                   7
       134:  beard                    ALPHA                   5
       135:  and                      ALPHA                   3
       136:  sparrow                  ALPHA                   7
       137:  hands                    ALPHA                   5
       138:  who                      ALPHA                   3
       139:  introduced               ALPHA                  10
       140:  himself                  ALPHA                   7
       141:  as                       ALPHA                   2
       142:  Melqu                    ALPHA                   5
       143:  ades                     ALPHA                   4
----- New Block ---------------------[119] bytes
put on a bold public demonstration of what he himself called the eighth wonder of the learned alchemists of Macedonia.

       144:  put                      ALPHA                   3
       145:  on                       ALPHA                   2
       146:  a                        ALPHA                   1
       147:  bold                     ALPHA                   4
       148:  public                   ALPHA                   6
       149:  demonstration            ALPHA                  13
       150:  of                       ALPHA                   2
       151:  what                     ALPHA                   4
       152:  he                       ALPHA                   2
       153:  himself                  ALPHA                   7
       154:  called                   ALPHA                   6
       155:  the                      ALPHA                   3
       156:  eighth                   ALPHA                   6
       157:  wonder                   ALPHA                   6
       158:  of                       ALPHA                   2
       159:  the                      ALPHA                   3
       160:  learned                  ALPHA                   7
       161:  alchemists               ALPHA                  10
       162:  of                       ALPHA                   2
       163:  Macedonia                ALPHA                   9



=============== END OF FILE ===============



Tokens Found: 163
==========
[       OK ] TEST_TOKENIZER.TestFTokenize (3 ms)
[----------] 2 tests from TEST_TOKENIZER (3 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (3 ms total)
[  PASSED  ] 2 tests.
*/